### ISSUE TITLE
Issue with WeatherProject

### ISSUE THREAD

**Issue by iksnae** [bonniee/learning-react-native#23]
I noticed the changes in book versus what's here in repo and decided to replace what I'd written by hand as I followed along. Unfortunately, when i ran the project I ended up with less than ideal results. Attached are the screenshots from iOS Simulator and Android Emulator.

<img width="688" alt="screen shot 2016-07-25 at 2 18 52 pm" src="https://cloud.githubusercontent.com/assets/799271/17117894/38860b24-5273-11e6-9132-ed1229bf146e.png">
<img width="621" alt="screen shot 2016-07-25 at 2 18 48 pm" src="https://cloud.githubusercontent.com/assets/799271/17117895/389e5ff8-5273-11e6-8cf1-c0e2f4af26b9.png">

I'd love to have been able to fix and submit pull request, but I'm just learning myself. Please let me know if I'm missing something or done something wrong. Thank you in advance for any help.

**Comment by gfd6th** [comment]
remove the style `flex: 1` in zipContainer and mainText

**Comment by neilyoung** [comment]
...and while you are doing this, change also the "flex: 2" in Forecast.js to "flex:1"

**Comment by edyu** [comment]
I found it better to just remove the "flex:" lines from inner views (i.e. Forecast.js).

**Comment by skyz319** [comment]
image is too big.... add code: "width: 375" in backdrop, issue is fix....
<img width="236" alt="img2" src="https://cloud.githubusercontent.com/assets/3850023/21008574/4062b53e-bd7d-11e6-8997-86175ad1c5b9.png">
<img width="236" alt="img2" src="https://cloud.githubusercontent.com/assets/3850023/21008575/4162101a-bd7d-11e6-8728-9eddebf57851.png">

**Comment by marsapolo** [comment]
LinkedStateMixin from /Users/marklee/Downloads/learning-react-native-master/WeatherProject/node_modules/react-native/Libraries/react-native/react-native.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/LinkedStateMixin and its parent directories

**Comment by ColinBinWang** [comment]
@skyz319 The key issue is the "Current weather for" is missing

**Comment by jialechan** [comment]
WeatherProject.js
```css
const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    paddingTop: 30
  },
  backdrop: {
    flexDirection: 'column'
  },
  overlay: {
    paddingTop: 5,
    backgroundColor: '#000000',
    opacity: 0.5,
    flexDirection: 'column',
    alignItems: 'center'
  },
  row: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'flex-start',
    padding: 30
  },
  zipContainer: {
    borderBottomColor: '#DDDDDD',
    borderBottomWidth: 1,
    marginLeft: 5,
    marginTop: 3
  },
  zipCode: {
    width: 50,
    height: baseFontSize,
    padding: 0
  },
  mainText: {
    fontSize: baseFontSize,
    color: '#FFFFFF'
  }
});
```

Forecast.js
```css
const styles = StyleSheet.create({
  bigText: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
    color: '#FFFFFF'
  },
  mainText: {
    fontSize: 16,
    textAlign: 'center',
    color: '#FFFFFF'
  }
})
```

In my case, change like this will ok
